# Generated by Django 4.2.7 on 2026-03-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendly_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('status_type', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_statuses',
            },
        ),
        migrations.AddField(
            model_name='coreuser',
            name='status_ref',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_users', to='vendly_backend.corestatus'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status_ref',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendly_backend.corestatus'),
        ),
    ]
