# Generated by Django 4.2.7 on 2026-03-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendly_backend', '0011_rename_chatreport_status_ref_to_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatreport',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports', to='vendly_backend.corestatus'),
        ),
    ]
