# Generated by Django 4.2.7 on 2026-03-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendly_backend', '0015_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vendor_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='vendly_backend.vendorpackage'),
        ),
    ]
