# Generated by Django 4.2.7

from django.db import migrations, models
from django.db.models import F
import django.db.models.deletion


def backfill_requested_by(apps, schema_editor):
    Booking = apps.get_model("vendly_backend", "Booking")
    Booking.objects.all().update(requested_by_id=F("customer_id"))


class Migration(migrations.Migration):

    dependencies = [
        ("vendly_backend", "0016_booking_vendor_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_bookings",
                to="vendly_backend.coreuser",
            ),
        ),
        migrations.RunPython(backfill_requested_by, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="booking",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_bookings",
                to="vendly_backend.coreuser",
            ),
        ),
    ]
