# Generated by Django 4.2.7 on 2026-03-25 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendly_backend', '0018_comment_is_hidden_vendorfollower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feeds',
            },
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to=settings.AUTH_USER_MODEL)),
                ('feed', models.ForeignKey(db_column='feed_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vendly_backend.feed')),
                ('parent_comment', models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='vendly_backend.feedcomment')),
            ],
            options={
                'db_table': 'feed_comments',
            },
        ),
        migrations.CreateModel(
            name='FeedDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(db_column='feed_id', on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='vendly_backend.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_dislikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_dislikes',
                'unique_together': {('feed', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(db_column='feed_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='vendly_backend.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_likes',
                'unique_together': {('feed', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FeedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('is_video', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('feed', models.ForeignKey(db_column='feed_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='vendly_backend.feed')),
            ],
            options={
                'db_table': 'feed_media',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postmedia',
            name='post',
        ),
        migrations.AddField(
            model_name='vendor',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='PostMedia',
        ),
        migrations.AddField(
            model_name='feed',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='vendly_backend.vendor'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='vendly_backend.feedcomment'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
