# Generated by Django 4.2.7 on 2026-03-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendly_backend', '0019_feed_feedcomment_feeddislike_feedlike_feedmedia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='dislike_count',
        ),
        migrations.DeleteModel(
            name='FeedDislike',
        ),
    ]
