# Generated by Django 4.2.7 on 2026-03-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendly_backend', '0022_booking_cancellation_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cancellation_reason',
            new_name='status_note',
        ),
    ]
