# Generated by Django 4.2.7 on 2026-03-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendly_backend', '0023_rename_cancellation_reason_booking_status_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
