# Generated by Django 4.2.7 on 2026-03-30 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendly_backend', '0024_category_cover_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_reports', to=settings.AUTH_USER_MODEL)),
                ('status_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_reports', to='vendly_backend.corestatus')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vendly_backend.vendor')),
            ],
            options={
                'db_table': 'vendor_reports',
            },
        ),
    ]
